import {
  Backpack,
  BookOpen,
  Circle,
  Clock,
  Cloud,
  Coffee,
  Compass,
  Ear,
  Eye,
  Feather,
  Footprints,
  Hand,
  HandHeart,
  Hash,
  Heart,
  Leaf,
  ListChecks,
  Map,
  MessageCircleHeart,
  Moon,
  Palette,
  PauseCircle,
  PersonStanding,
  Quote,
  RefreshCw,
  ScanLine,
  Shuffle,
  Sparkles,
  Sprout,
  Square,
  TrendingUp,
  Sun,
  Waves,
  Wind,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import type { SessionIcon as SessionIconKey } from './course'

const ICONS: Record<SessionIconKey, LucideIcon> = {
  sprout: Sprout,
  ear: Ear,
  pause: PauseCircle,
  refresh: RefreshCw,
  wind: Wind,
  square: Square,
  waves: Waves,
  hash: Hash,
  scan: ScanLine,
  hand: Hand,
  heart: Heart,
  move: PersonStanding,
  leaf: Leaf,
  quote: Quote,
  book: BookOpen,
  cloud: Cloud,
  eye: Eye,
  footprints: Footprints,
  palette: Palette,
  'heart-hand': HandHeart,
  message: MessageCircleHeart,
  sparkles: Sparkles,
  moon: Moon,
  list: ListChecks,
  feather: Feather,
  shuffle: Shuffle,
  clock: Clock,
  circle: Circle,
  stairs: TrendingUp,
  sun: Sun,
  compass: Compass,
  coffee: Coffee,
  map: Map,
  story: BookOpen,
  backpack: Backpack,
}

/** A session's icon on its stone. */
function SessionIcon({ icon, size = 28 }: { icon: SessionIconKey; size?: number }) {
  const Icon = ICONS[icon] ?? Sprout
  return <Icon size={size} strokeWidth={2.4} />
}

export { SessionIcon }
